parameters:
    module_manager_service.class: OD\VdmBundle\Service\ModuleManager
    config_manager_service.class: OD\VdmBundle\Service\ConfigManager

services:
    module.manager:
        class: '%module_manager_service.class%'
    config.manager:
        class: '%config_manager_service.class%'
        arguments: ['@module.manager', '@translator']
