parameters:
    od_ldap.client.class: Zend\Ldap\Ldap
    od_ldap.user_manager.class: OD\LdapBundle\Security\User\LdapUserManager
    od_ldap.user_provider.class: OD\LdapBundle\Security\User\LdapUserProvider
    od_ldap.client.options:
    od_ldap.user_manager.user_base_dn:
    od_ldap.user_manager.user_filter:
    od_ldap.user_manager.username_attribute:
    od_ldap.user_manager.role_base_dn:
    od_ldap.user_manager.role_filter:
    od_ldap.user_manager.role_name_attribute:
    od_ldap.user_manager.role_user_attribute:
    od_ldap.user_provider.role_prefix:
    od_ldap.user_provider.default_roles:

services:
    od_ldap.client:
        class: %od_ldap.client.class%
        arguments:
            - %od_ldap.client.options%
    od_ldap.user_manager:
        class: %od_ldap.user_manager.class%
        arguments:
            - '@od_ldap.client'
            - %od_ldap.user_manager.user_base_dn%
            - %od_ldap.user_manager.user_filter%
            - %od_ldap.user_manager.username_attribute%
            - %od_ldap.user_manager.role_base_dn%
            - %od_ldap.user_manager.role_filter%
            - %od_ldap.user_manager.role_name_attribute%
            - %od_ldap.user_provider.default_roles%
    od_ldap.user_provider:
        class: %od_ldap.user_provider.class%
        arguments:
            - '@od_ldap.user_manager'
            - %od_ldap.user_provider.role_prefix%
            - %od_ldap.user_provider.default_roles%