parameters:
    base_src: http://localhost/vdm
    vdm_src: "%base_src%/web/bundles/odvdm/js/Vdm"
    ticket_src: "%base_src%/web/bundles/odticket/js/Ticket"

    database_driver:     pdo_mysql
    database_host:       127.0.0.1
    database_port:       ~
    database_name:       vdm
    database_user:       root
    database_password:   ~

    mailer_transport:    smtp
    mailer_host:         127.0.0.1
    mailer_user:         ~
    mailer_password:     ~

    locale:              fr
    secret:              ThisTokenIsNotSoSecretChangeIt

    active_directory.settings:
        account_suffix : viseo.net
        base_dn : DC=viseo,DC=net       #The DN of the domain
        domain_controllers :
            - 172.30.251.47
        admin_username:
        admin_password:
        real_primarygroup : true        #For Linux compatibility.
        use_ssl : false
        use_tls : false
        recursive_groups : false        #Used Only for group test (not userInfo)
        sso : false                     #Use NTML. Not yet compatible with Symfony !!!
        username_patterns:              #username is extracted from the string the user put into the login form
            - /([^@]*)@viseo.net/i      #like toto@viseo.net
            - /VISEO\\(.*)/i            #like VISEO\toto
            - /VISEO.NET\\(.*)/i        #like VISEO.NET\toto
            - /(.*)/i                   #like toto
