<?php

namespace OD\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomingCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingCallRepository extends EntityRepository
{

    /**
     * Find all phone lines
     *
     * @param stdClass $sort
     *
     * @return array
     */
    public function findAllQuery($sort)
    {
        $qBuilder = $this->_em->createQueryBuilder()
            ->select("
                i.idkey,
                DATE_FORMAT(i.date, '%d/%m/%Y %H:%i:%s') as date,
                i.duration,
                i.callingNumber,
                i.nature,
                pl.number as phoneLine")
            ->from('Ticket:IncomingCall', 'i')
            ->leftJoin('i.phoneLine', 'pl');

        if ($sort) {
            $prefix = $sort->property == 'number' ? 'pl.' : 'i.';
            $qBuilder->addOrderBy($prefix . $sort->property, $sort->direction);
        }

        return $qBuilder->getQuery();
    }

}
