<?php

namespace OD\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomingCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingCallRepository extends EntityRepository
{

    /**
     * Find all phone lines
     *
     * @return array
     */
    public function findAllArray()
    {
        $qBuilder = $this->_em->createQueryBuilder()
            ->select("
                i.idkey,
                DATE_FORMAT(i.date, '%d/%m/%Y %H:%i:%s') as date,
                i.duration,
                i.callingNumber,
                i.nature,
                pl.number as phoneline")
            ->from('Ticket:IncomingCall', 'i')
            ->leftJoin('i.phoneLine', 'pl');

        return $qBuilder->getQuery()->getArrayResult();
    }

}
