<?php

namespace OD\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneLineRepository extends EntityRepository
{

    /**
     * Find all phone lines
     *
     * @return array
     */
    public function findAllArray()
    {
        $qBuilder = $this->_em->createQueryBuilder()
            ->select('pl')
            ->from('Ticket:PhoneLine', 'pl');

        return $qBuilder->getQuery()->getArrayResult();
    }

}
