<?php

namespace OD\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneLineRepository extends EntityRepository
{

    /**
     * Find all phone lines
     *
     * @param stdClass $sort
     *
     * @return array
     */
    public function findAllQuery($sort)
    {

        $qBuilder = $this->_em->createQueryBuilder()
            ->select('pl')
            ->from('Ticket:PhoneLine', 'pl');

        if ($sort) {
            $qBuilder->addOrderBy('pl.' . $sort->property, $sort->direction);
        }

        return $qBuilder->getQuery();
    }

}
